### ISSUE TITLE
Document Translation

### ISSUE THREAD

**Issue by chenhg5** [GoAdminGroup/docs#1]
## Volunteer Wanted

Hey, guys! We are going to provide documentations of more other languages.

But we are short of staff :-( So, we want some volunteers to help us to translate the documentation into other languages. Every translation task needs a translator and a reviewer. Both of them are expected that they had used the GoAdmin in the real world.

### Translator

A translator should be familiar with both Chinese or English and the language that you want to translate into.

If you want to be a volunteer translator, just comment on this issue. For example, "I want to be the translator of English install.md ....". And then, we will update this issue.

Premise:

- [docs site](https://book.go-admin.cn)
- [docs github](https://github.com/GoAdminGroup/docs)

Contributing:

1. Fork
2. Create a branch starting at the master and name it as translation-[xxx].
3. Find Markdown files.
4. Just translate it.
5. Create a pull request when your translation is done, and ping your reviewer.
6. docs: request to docs: master.
7. PR will be merged if your reviewer think it is OK.

### TODOs:

- [ ] English (translator: @ reviewer:@ )
- [ ] 日本語 (translator: @ reviewer:@ )
- [ ] Français (translator: @Ectalite reviewer:@ )
- [ ] Русский (translator: @ reviewer:@ )
- [ ] Türkçe (translator: @ reviewer:@ )
- [ ] العَرَبِيَّة (translator: @ reviewer:@ )
- [ ] español (translator: @ reviewer:@ )
- [ ] Português (translator: @ reviewer:@ )
- [ ] Türkçe(translator: @ilketaha reviewer:@fakturk )
- [ ] Ukrainian (translator: @Vova-Kozak reviewer:@Vova-Kozak )
- [ ] etc....

**Comment by Ectalite** [comment]
Will see if I can help for french translation

**Comment by chenhg5** [comment]
> Will see if I can help for french translation

@Ectalite cool! I will complete the English documents today and copy the directory to a french directory. And you can translate it according to the English documents, file by file. thx.

@Ectalite I have created the fr directory. #2

**Comment by hmert** [comment]
@Ectalite Hi, add @ilketaha and me as a translator for Turkish. And @fakturk will be our reviewer. We will be also contributor for GoAdmin!

**Comment by chenhg5** [comment]
> @Ectalite Hi, add @ilketaha and me as a translator for Turkish. And @fakturk will be our reviewer. We will be also contributor for GoAdmin!

@hmert I have added to the list. Thanks.

**Comment by hmert** [comment]
@chenhg5 Türkçe = Turkish

**Comment by chenhg5** [comment]
@hmert Ok,  you can contact me in real-time by joining [slack](http://goadmin.slack.com) or [telegram](https://t.me/joinchat/NlyH6Bch2QARZkArithKvg)

**Comment by Vova-Kozak** [comment]
Can you add ukrainian language to the list?

**Comment by chenhg5** [comment]
@Vova-Kozak Yes, of course. Would you like to help to translate into the ukrainian language?

**Comment by chenhg5** [comment]
@Vova-Kozak Yes, of course. Would you like to help to translate into the ukrainian language?

**Comment by Vova-Kozak** [comment]
@chenhg5 I'd like to try)

**Comment by chenhg5** [comment]
> @chenhg5 I'd like to try)

👌

**Comment by dongft** [comment]
No Chinese language?

**Comment by mirusky** [comment]
I can help with Brazilian Portuguese translation, what I need to do?

**Comment by sandyQxDatuk** [comment]
I can help with Indonesian translation

**Comment by craph** [comment]
Hi @chenhg5,

I can help for the french translation and I know someone who is an english teacher to help for the english translation if needed.

Do you need help ?

**Comment by iryek219** [comment]
Hi @chenhg5, 
Could you let me work on Korean translation?

**Comment by craph** [comment]
@chenhg5 did you see my comment from Nov 19, 2020 ? https://github.com/GoAdminGroup/docs/issues/1#issuecomment-730551189

**Comment by Ucag** [comment]
我英语专八, 可以帮忙翻译一部分. 但是需要 maintainer 给个翻译计划什么的, 好方便和项目进展同步.

**Comment by Ectalite** [comment]
> > Will see if I can help for french translation
> 
> @Ectalite cool! I will complete the English documents today and copy the directory to a french directory. And you can translate it according to the English documents, file by file. thx.
> 
> @Ectalite I have created the fr directory. #2

I only saw it now, it must be a bug from GitHub. I'm really sorry. I will begin soon

**Comment by camilovietnam** [comment]
Hello, I will start using the Go Admin package in our system, so after a few weeks I will have experience with it and I could volunteer to be a translator or reviewer for the Spanish language.

**Comment by perry19** [comment]
Hello @everyone. I can assist with French translation. With what can I begin?

**Comment by Ucag** [comment]
您好，我是李冬，您发来的邮件已收到，我将会尽快回复您

**Comment by Ectalite** [comment]
@perry19 if you want I started a fork on my github.

**Comment by perry19** [comment]
Alright, I'll have everything setup by tomorrow. should I fork this repo and create a branch from master or you will share your repo for me to fork?

**Comment by Ectalite** [comment]
If you want, you can work on my fork. I will add you as maintainer so you will have rights to modify files. 
Edit: I‘ve send you a invite.

**Comment by perry19** [comment]
Hi @Ectalite  I just saw your invitation

**Comment by Ectalite** [comment]
You should be able to modify files now.

**Comment by perry19** [comment]
Exactly, I just cloned your repo following the invitation. I'll pick a .md file and begin translation.

**Comment by roozbehsayadi** [comment]
Hi.
I would like to add Persian to this package.
I'm talking about the contents of this folder: https://github.com/GoAdminGroup/go-admin/tree/master/modules/language, not the documentations.
Is it OK?

**Comment by vghoffmann** [comment]
Hello, I would like to assist with the Brazilian Portuguese translation.

**Comment by Ucag** [comment]
您好，我是李冬，您发来的邮件已收到，我将会尽快回复您

**Comment by xpierroz** [comment]
I want to be a french translator
